name: Apply

on:
  workflow_dispatch:

env:
  TF_VAR_billing_account_id: "${{ secrets.BILLING_ACCOUNT_ID }}"
  TF_VAR_seed_sa_email_address: "${{ secrets.SEED_SA_EMAIL_ADDRESS }}"
  TF_VAR_github_admin_token: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
  TF_VAR_project_postfix: "${{ secrets.GCP_PROJECT_POSTFIX }}"
  TF_IN_AUTOMATION: "true"
  GITHUB_TOKEN: "${{ secrets.ADMIN_GITHUB_TOKEN }}"

permissions:
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v0.6.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          # todo: replace with seed SA / (need to configure workload id pool)
          service_account: ${{ secrets.SEED_SA_EMAIL_ADDRESS }}
          token_format: 'access_token'
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Init
        run: terraform init
      - name: Check security
        uses: triat/terraform-security-scan@v3.0.1
      - name: Apply
        run: terraform apply --auto-approve
