name: Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setting up GCP environment
      #   uses: google-github-actions/setup-gcloud@v0.2.1
      #   with:
      #     project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #     service_account_key: "${{ secrets.GCR_SA_KEY }}"
      #     export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Init
        run: terraform init
      - name: Apply
        run: terraform apply --auto-approve
        env:
          TF_VAR_billing_account_id: "${{ secrets.BILLING_ACCOUNT_ID }}"
