name: Plan infrastructure

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  workflow_dispatch:

jobs:
  compliance-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setting up GCP environment
      #   uses: google-github-actions/setup-gcloud@v0.2.1
      #   with:
      #     project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #     service_account_key: "${{ secrets.GCR_SA_KEY }}"
      #     export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.641.0
        with:
          framework: terraform
          output_format: cli
          download_external_modules: true

  security-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setting up GCP environment
      #   uses: google-github-actions/setup-gcloud@v0.2.1
      #   with:
      #     project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #     service_account_key: "${{ secrets.GCR_SA_KEY }}"
      #     export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: tfsec
        uses: triat/terraform-security-scan@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setting up GCP environment
      #   uses: google-github-actions/setup-gcloud@v0.2.1
      #   with:
      #     project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #     service_account_key: "${{ secrets.GCR_SA_KEY }}"
      #     export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Validate
        run: terraform validate -no-color

  plan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setting up GCP environment
      #   uses: google-github-actions/setup-gcloud@v0.2.1
      #   with:
      #     project_id: "${{ secrets.GCP_PROJECT_ID }}"
      #     service_account_key: "${{ secrets.GCR_SA_KEY }}"
      #     export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Init
        run: terraform init
      - name: Plan
        run: terraform plan -no-color
        env:
          TF_VAR_billing_account_id: "${{ secrets.BILLING_ACCOUNT_ID }}"