name: Test

on:
  workflow_dispatch:

env:
  CLOUDSDK_CORE_PROJECT: ${{ secrets.BASELINE_PROJECT_ID }}

permissions:
  id-token: write

jobs:
  test-login:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v0.8.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SEED_SA_EMAIL_ADDRESS }}
          token_format: "access_token"
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.6.0
      - run: gcloud auth print-identity-token
