name: Wi-Test

on:
  workflow_dispatch:

env:
  WORKLOAD_IDENTITY_PROVIDER: "projects/577705814230/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
  TF_VAR_billing_account_id: "${{ secrets.BILLING_ACCOUNT_ID }}"
  TF_VAR_seed_sa_email_address: "${{ secrets.SEED_SA_EMAIL_ADDRESS }}"
  TF_VAR_github_admin_token: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
  TF_VAR_project_postfix: "${{ secrets.GCP_PROJECT_POSTFIX }}"
  TF_IN_AUTOMATION: "true"
  GITHUB_TOKEN: "${{ secrets.ADMIN_GITHUB_TOKEN }}"

jobs:
  plan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: Authenticating
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: $WORKLOAD_IDENTITY_PROVIDER
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
      - name: Init
        run: terraform init
      - name: Plan
        run: terraform plan -no-color
